# syntax=docker/dockerfile:1.4
FROM ubuntu:latest

RUN apt update && apt install -y curl tcpdump openssl

RUN mkdir /shared
VOLUME ["/shared"]
CMD tail -f /dev/null

# COPY --from=server-container /shared/client.crt /shared/
# COPY --from=server-container /shared/client.key /shared/