services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-container
    volumes:
      - shared:/shared

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client-container
    volumes:
      - shared:/shared
    depends_on:
      - server

volumes:
  shared: