FROM ubuntu:latest

# Install necessary tools
RUN apt update && apt install -y curl tcpdump

# Create necessary directories for certificates
RUN mkdir -p /etc/ssl/certs /etc/ssl/private /shared

# Copy certificates into appropriate directories (shared volume will mount these)
CMD ["bash"]